### ISSUE TITLE
getState is not a function error

### ISSUE THREAD

**Issue by elaijuh** [teropa/ngrx-hotload-rc5#1]
When I just follow the steps to set everything up, and change the source code, I see this error

```
zone.js:484 Unhandled Promise rejection: getState(...) is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: getState(...) is not a function(…) TypeError: getState(...) is not a function
```

**Comment by teropa** [comment]
Do you have the `getState` function as in here? https://github.com/teropa/ngrx-hotload-rc5/blob/master/src/hot-store.ts#L33

The error message sounds like it might be missing.

**Comment by elaijuh** [comment]
Yes it's there, that's weird. And this plugin only hot reload the ngrx store right? For components hot reload, I still need to use `angular2-hmr`

**Comment by teropa** [comment]
Interesting, I haven't run into this and the code as posted in this repo does work for me.

The solution reloads the whole application, including components and everything else.

**Comment by elaijuh** [comment]
```
 module.hot.dispose((data: any) => {
    console.time('dispose');
    const store: Store<any> = MODULE_REF.injector.get(Store);
    appState = getState(store);
    (<any>Object).assign(data, { appState  });
    console.timeEnd('dispose');
  });
```

I cannot see any code that store the components, can you point me to there?

**Comment by teropa** [comment]
It does not store anything about components because it does not need to.

When all state is kept in the ngrx/store, the new application (including new components) will load into the exact same state as the previous one. The only thing that needs to be kept is the store state.

**Comment by elaijuh** [comment]
From `angular2-hmr` the components are manually stored before destroy

```
hmrOnDestroy(store) {
    var cmpLocation = this.appRef.components.map(cmp => cmp.location.nativeElement)
    // recreate elements
    store.disposeOldHosts = createNewHosts(cmpLocation)
    // inject your AppStore and grab state then set it on store
    // var appState = this.AppStore.get()
    // let appState: any

    this._store.take(1).subscribe(s => store.appState = s)
    store.OHHAI = 'yolo'
    // Object.assign(store, appState)
    // remove styles
    removeNgStyles()
  }
```

Which you mean is I need to store all components in ngrx/store manually ?

**Comment by teropa** [comment]
Ah, you mean the host elements of the root component(s)? Yes, you'll need to do that.
